version: '3.8'


services:
  bookmark-db:
    image: postgres:11-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=bookmark
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookmark-db
    networks:
      - bmknet
  test-db:
    image: postgres:11-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=bookmark
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-db
    networks:
      - bmknet

networks:
  bmknet:
