version: '3.8'


services:
  bookmark-db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=bookmark
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=bookmark-db
      - POSTGRES_DB=bookmark-db
    networks:
      - bmknet
networks:
  bmknet:
